language: java

matrix:
  include:
    # License, formatter, and FindBugs check
    - env: NAME="License, formatter, and FindBugs check"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn license:check
        - mvn formatter:validate
        - mvn findbugs:check

    # Coverage report
    - env: NAME="Coverage report"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn cobertura:cobertura -Denforcer.skip=true
      after_success:
        - mvn coveralls:report

    # Linux tests (Java 8 LTS)
    - env: NAME="Linux tests (Java 8)"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn test -Denforcer.skip=true

    # Linux tests (Java 9)
    - env: NAME="Linux tests (Java 9)"
      os: linux
      sudo: false
      jdk: openjdk9
      script:
        - mvn test -Denforcer.skip=true

    # Linux tests (Java 10)
    - env: NAME="Linux tests (Java 10)"
      os: linux
      sudo: false
      script:
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - source ./install-jdk.sh -F 10 -L GPL
        - mvn test -Denforcer.skip=true

    # macOS tests
    - env: NAME="macOS tests"
      os: osx
      osx_image: xcode9.2
      script:
        - mvn test -Denforcer.skip=true

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

before_install:
  - rm ~/.m2/settings.xml || true # remove the default settings.xml in order to use custom repos
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source .travis/linux_start_xvfb.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then .travis/macos_install_jdk8.sh; fi
